version: '3.8'

services:
  # llm:
  #   build: ./llm
  #   container_name: tinyllama-vllm
  #   ports:
  #     - "11434:11434"
  #   runtime: nvidia
  #   environment:
  #     - HF_HUB_ENABLE_HF_TRANSFER=1
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   restart: unless-stopped

  rag:
    build: ./rag
    container_name: rag-service
    ports:
      - "8000:8000"
    # depends_on:
    #   - llm
    environment:
      - RAG_SERVICE_URL=http://llm:11434
    restart: unless-stopped
    volumes:
      - ./rag:/app

  backend:
    build: ./backend
    container_name: resume-backend
    ports:
      - "8001:8001"
    # depends_on:
    #   - llm
    environment:
      - OLLAMA_BASE_URL=http://llm:11434
      - APP_ENV=development
    restart: unless-stopped
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: resume-frontend
    ports:
      - "3000:3000"   # map host:container
    restart: unless-stopped
    environment:
      # - PORT=80
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]   # Override CMD here for dev hot reload


  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   # depends_on:
  #   #   - resume-frontend
  #   #   - resume-backend

  nginx_llm:
    build:
      context: ./nginx_llm
      dockerfile: Dockerfile

    ports:
      - "8080:80"
    volumes:
    - ./nginx_llm/nginx.dev.conf:/etc/nginx/nginx.conf:ro

    healthcheck:
      test: >
        curl --fail --silent http://localhost:11434/api/generate 
        -H "Content-Type: application/json" 
        -d '{"model":"mistral","prompt":"ping","stream":false}' 
        | grep -q '"done":true'
      interval: 30s
      timeout: 10s
      retries: 5


# Optional volumes - remove if not used
# volumes:
#   ollama_data:
