services:
  - type: web
    name: rag-service
    env: docker
    plan: starter
    dockerfilePath: RAG/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: RAG_SERVICE_URL
        value: http://llm:11434  # Placeholder for now
    autoDeploy: true

  - type: web
    name: resume-backend
    env: docker
    plan: starter
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: OLLAMA_BASE_URL
        value: http://llm:11434  # Placeholder
    autoDeploy: true

  - type: web
    name: resume-frontend
    env: docker
    plan: starter
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: "80"
      - key: NODE_ENV
        value: development
      - key: CHOKIDAR_USEPOLLING
        value: "true"
    autoDeploy: true

  - type: web
    name: nginx
    env: docker
    plan: starter
    dockerfilePath: nginx/Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
